<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_makanan</name>
   <tag></tag>
   <elementGuidId>18d20efa-4907-4714-ac3e-60ba2aca2c8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-2613-76 > div.v-list-item__content > div.v-list-item__title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;list-item-2613-76&quot;)/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__title&quot;][count(. | //*[(text() = 'makanan' or . = 'makanan')]) = count(//*[(text() = 'makanan' or . = 'makanan')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-2613-76']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ae45dd2-1881-40f9-a323-63cb3696f34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__title</value>
      <webElementGuid>be4b192f-eb14-4c9a-a587-b4d466a02f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>makanan</value>
      <webElementGuid>cb2aae21-d632-473c-ac45-590c3d8be724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-2613-76&quot;)/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__title&quot;]</value>
      <webElementGuid>8cb690d9-7138-43a0-8ad2-69616f8935fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-2613-76']/div/div</value>
      <webElementGuid>ca088c79-48be-4a89-918d-4b194ab08ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testes'])[10]/following::div[3]</value>
      <webElementGuid>573d15ff-3fa5-48ac-b286-8f67aace8682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[38]/following::div[6]</value>
      <webElementGuid>4e11416b-039d-43a2-a167-1b5f967936c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[39]/preceding::div[1]</value>
      <webElementGuid>fce96d06-def2-4130-b486-463331a55327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[40]/preceding::div[4]</value>
      <webElementGuid>f39e97de-0df0-4eb1-9f07-a295baee7578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='makanan']/parent::*</value>
      <webElementGuid>3a416140-34a7-4633-9e8d-3649d1ea3fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[77]/div/div</value>
      <webElementGuid>83129a6a-7977-43a3-94a4-543326ffb567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'makanan' or . = 'makanan')]</value>
      <webElementGuid>0f93df18-59d4-4725-8ad5-8cc0b581e342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-1929-76']/div/div</value>
      <webElementGuid>0c80834b-fa24-49c3-9132-610897f4d546</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
